export const ETH_MGO_ABI = {
    'CA': "0x6866b4923fc3fe89ac10b3ef0ab7e9ef5fc00dca",
    'ABI': [{
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "address",
            "name": "destination",
            "type": "address"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "toToken",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "amountOut",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "string",
            "name": "fromToken",
            "type": "string"
        }, {
            "indexed": false,
            "internalType": "string",
            "name": "bridgeHash",
            "type": "string"
        }],
        "name": "TokenClaimed",
        "type": "event"
    }, {
        "anonymous": false,
        "inputs": [{
            "indexed": true,
            "internalType": "address",
            "name": "sender",
            "type": "address"
        }, {
            "indexed": true,
            "internalType": "address",
            "name": "fromToken",
            "type": "address"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "amountIn",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "fee",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "string",
            "name": "toToken",
            "type": "string"
        }, {
            "indexed": false,
            "internalType": "string",
            "name": "destination",
            "type": "string"
        }],
        "name": "TokenDeposited",
        "type": "event"
    }, {
        "inputs": [{
            "components": [{
                "internalType": "address",
                "name": "fromToken",
                "type": "address"
            }, {
                "internalType": "uint256",
                "name": "amountIn",
                "type": "uint256"
            }, {
                "internalType": "string",
                "name": "toToken",
                "type": "string"
            }, {
                "internalType": "string",
                "name": "destination",
                "type": "string"
            }],
            "internalType": "struct BridgeMessage.BridgeTokenMessage",
            "name": "message",
            "type": "tuple"
        }],
        "name": "bridgeToken",
        "outputs": [],
        "stateMutability": "payable",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "string",
            "name": "",
            "type": "string"
        }, {
            "internalType": "string",
            "name": "",
            "type": "string"
        }],
        "name": "claimTime",
        "outputs": [{
            "internalType": "uint256",
            "name": "",
            "type": "uint256"
        }],
        "stateMutability": "view",
        "type": "function"
    }, {
        "inputs": [{
            "internalType": "bytes[]",
            "name": "signatures",
            "type": "bytes[]"
        }, {
            "components": [{
                "internalType": "address",
                "name": "toToken",
                "type": "address"
            }, {
                "internalType": "address",
                "name": "destination",
                "type": "address"
            }, {
                "internalType": "uint256",
                "name": "amountOut",
                "type": "uint256"
            }, {
                "internalType": "string",
                "name": "fromToken",
                "type": "string"
            }, {
                "internalType": "string",
                "name": "bridgeHash",
                "type": "string"
            }],
            "internalType": "struct BridgeMessage.ClaimTokenMessage",
            "name": "message",
            "type": "tuple"
        }],
        "name": "claimToken",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function"
    }]
};

